export { default as callIcon } from './call-icon.svg'
export { default as headphoneIcon } from './headphone-icon.svg'

export { default as secureIcon } from './secure-icon.svg'
export { default as vkIcon } from './vk-icon.svg'
export { default as avitoIcon } from './avito-icon.svg'
export { default as maxIcon } from './max-icon.svg'
export { default as tgIcon } from './tg-icon.svg'
export { SuccessIcon } from './success-icon'
export { default as RightArrowIcon } from './right-arrow-icon.svg'
export { CloseIcon } from './CloseIcon'
export { default as secure2Icon } from './secure-2-icon.svg'
export { default as sparkesIcon } from './sparkles-icon.svg'
export { default as fastIcon } from './fast-icon.svg'

export * from './profile-icon'
export * from './wallet-icon'
export * from './apps-icon'
export * from './plus-icon'
export * from './delete-icon'
export * from './exit-icon'
export * from './download-icon'
export * from './timer-icon'
