import type { ICatalogApps } from '../types'
import {
  chatgpt,
  claude,
  deepseek,
  grok,
  max,
  ozonbank,
  perplexity,
  rutube,
  sber,
  wbbank,
  mailru,
  yandexPay,
  vk,
  avito,
  megamarket,
  youla,
  happ,
} from '../images/index'

export const CATALOG_APPS: ICatalogApps[] = [
  {
    id: 'vk',
    icon: vk,
    name: 'Вконтакте',
    type: 'Социальные сети',
  },
  {
    id: 'max',
    icon: max,
    name: 'MAX',
    type: 'Социальные сети',
  },
  {
    id: 'yandexPay',
    icon: yandexPay,
    name: 'Яндекс Пэй',
    type: 'Финансы',
  },
  {
    id: 'ozonBank',
    icon: ozonbank,
    name: 'Ozon Bank',
    type: 'Финансы',
  },
  {
    id: 'sber',
    icon: sber,
    name: 'Сбербанк',
    type: 'Финансы',
  },
  {
    id: 'wbbank',
    icon: wbbank,
    name: 'WB банк',
    type: 'Финансы',
  },
  {
    id: 'avito',
    icon: avito,
    name: 'Авито',
    type: 'Покупки',
  },
  {
    id: 'mailru',
    icon: mailru,
    name: 'Почта Mail',
    type: 'Утилиты',
  },
  {
    id: 'happ',
    icon: happ,
    name: 'Happ',
    type: 'Утилиты',
  },
  {
    id: 'claude',
    icon: claude,
    name: 'Claude',
    type: 'Утилиты',
  },
  {
    id: 'ula',
    icon: youla,
    name: 'Юла',
    type: 'Покупки',
  },
  {
    id: 'megamarket',
    icon: megamarket,
    name: 'Мегамаркет',
    type: 'Покупки',
  },
  {
    id: 'rutube',
    icon: rutube,
    name: 'Rutube',
    type: 'Фото и видео',
  },
  {
    id: 'chatgpt',
    icon: chatgpt,
    name: 'ChatGPT',
    type: 'Утилиты',
  },
  {
    id: 'perplexity',
    icon: perplexity,
    name: 'Perplexity',
    type: 'Утилиты',
  },
  {
    id: 'deepseek',
    icon: deepseek,
    name: 'DeepSeek',
    type: 'Утилиты',
  },
  {
    id: 'grok',
    icon: grok,
    name: 'Grok',
    type: 'Утилиты',
  },
]
